---
abstract: 'FastCGI Server'
author:
  - 'Árpád Szász <arpad.szasz@plenum.ro>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojo-Server-FastCGI
requires:
  Mojolicious: 3.0
resources:
  bugtracker: https://github.com/arpadszasz/mojo-server-fastcgi/issues
  repository: git://github.com/arpadszasz/mojo-server-fastcgi.git
version: 0.3
